import {createConstants} from '../utils';

export default createConstants(
    'LOGIN_USER_REQUEST',
    'LOGIN_USER_FAILURE',
    'LOGIN_USER_SUCCESS',
    'DATA_ADDED_SUCCESSFULLY',
    'FETCH_ACCOUNT_DATA_REQUEST',
    'FETCH_ACCOUNT_DATA_REQUEST_COMPLETE',
    'FETCH_ACCOUNT_DATA_REQUEST_FAILURE',
    'SHOW_LOGIN',
    'SHOW_SIGN_UP',
    'SHOW_HOME',
    'CIRCLE_STATUS_ADDED',
    'SHOW_NAVIGATION_MENU',
    'HIDE_NAVIGATION_MENU',
    'FETCH_SUBSCRIPTIONS',
    'FETCH_PRODUCTS_AND_PLANS'
);
