import {createConstants} from '../utils';

export default createConstants(
    'LOGIN_USER_REQUEST',
    'LOGIN_USER_FAILURE',
    'LOGIN_USER_SUCCESS',
    'DATA_ADDED_SUCCESSFULLY',
    'FETCH_ACCOUNT_DATA_REQUEST',
    'FETCH_ACCOUNT_DATA_REQUEST_COMPLETE',
    'FETCH_ACCOUNT_DATA_REQUEST_FAILURE',
    'SHOW_LOGIN',
    'SHOW_HOME'
);
